import styled from '@emotion/styled'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Card = styled.a`
  margin: 1rem;
  padding: 1.5rem;
  text-align: left;
  color: inherit;
  text-decoration: none;
  border: 1px solid #eaeaea;
  border-radius: 10px;
  transition: color 0.15s ease, border-color 0.15s ease;
  max-width: 300px;
  &:hover,
  &:focus,
  &:active {
    color: #0070f3;
    border-color: #0070f3;
  }
`
const CardTitle = styled.h2`
  margin: 0 0 1rem 0;
  font-size: 1.5rem;
`
const CardContent = styled.p`
  margin: 0;
  font-size: 1.25rem;
  line-height: 1.5;
`

const Home: NextPage = () => {
  return (
    <div className="py-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen px-16 flex-1 flex flex-col place-content-center">
        <div className="text-5xl text-center m-8">
          Welcome to{' '}
          <a
            href="https://nextjs.org"
            className="text-sky-500 no-underline hover:no-underline focus:no-underline active:no-underline"
          >
            Next.js!
          </a>
        </div>
        <p className="mx-16 my-4 text-base text-center">
          Get started by editing{' '}
          <code className="bg-neutral-600 border-r-4 p-3 text-lg font-mono">
            pages/index.tsx
          </code>
        </p>
        <div className="flex content-center justify-center flex-wrap max-w-screen-md mx-auto">
          <Card href="https://nextjs.org/docs">
            <CardTitle>Documentation &rarr;</CardTitle>
            <CardContent>
              Find in-depth information about Next.js features and API.
            </CardContent>
          </Card>

          <Card href="https://nextjs.org/learn">
            <CardTitle>Learn &rarr;</CardTitle>
            <CardContent>
              Learn about Next.js in an interactive course with quizzes!
            </CardContent>
          </Card>

          <Card href="https://github.com/vercel/next.js/tree/canary/examples">
            <CardTitle>Examples &rarr;</CardTitle>
            <CardContent>
              Discover and deploy boilerplate example Next.js projects.
            </CardContent>
          </Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <CardTitle>Deploy &rarr;</CardTitle>
            <CardContent>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </CardContent>
          </Card>
        </div>
      </main>

      <footer className="flex flex-1 px-2 border-t border-solid border-zinc-200 justify-center content-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center content-center grow"
        >
          Powered by{' '}
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
